import '../models/product_model.dart';

class DummyData {
  static List<ProductModel> getProducts() {
    return [
      ProductModel(
        id: '1',
        title: 'آيفون 15 برو ماكس 256GB',
        description: 'هاتف أيفون جديد بالكامل مع ضمان سنة، شاشة 6.7 بوصة، كاميرا 48 ميجابكسل',
        price: 450000,
        oldPrice: 500000,
        currency: 'YER',
        images: ['https://picsum.photos/id/1/300/300', 'https://picsum.photos/id/2/300/300'],
        category: 'إلكترونيات',
        subCategory: 'هواتف',
        sellerId: 'seller1',
        sellerName: 'متجر التقنية',
        sellerRating: 4.8,
        inStock: true,
        rating: 4.8,
        reviewCount: 120,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '2',
        title: 'سامسونج S24 الترا',
        description: 'هاتف سامسونج جالاكسي S24 الترا، شاشة 6.8 بوصة، كاميرا 200 ميجابكسل',
        price: 380000,
        oldPrice: 420000,
        currency: 'YER',
        images: ['https://picsum.photos/id/3/300/300'],
        category: 'إلكترونيات',
        subCategory: 'هواتف',
        sellerId: 'seller1',
        sellerName: 'متجر التقنية',
        sellerRating: 4.7,
        inStock: true,
        rating: 4.7,
        reviewCount: 95,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '3',
        title: 'لابتوب ماك بوك برو M3',
        description: 'لابتوب احترافي بشريحة M3، 16 جيجا رام، 512 جيجا SSD',
        price: 1800000,
        currency: 'YER',
        images: ['https://picsum.photos/id/5/300/300'],
        category: 'إلكترونيات',
        subCategory: 'لابتوب',
        sellerId: 'seller2',
        sellerName: 'الحاسوب المتقدم',
        sellerRating: 4.9,
        inStock: true,
        rating: 4.9,
        reviewCount: 45,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '4',
        title: 'تويوتا كامري 2024',
        description: 'سيارة تويوتا كامري 2024، مكيف أوتوماتيك، كاميرا خلفية',
        price: 8500000,
        currency: 'YER',
        images: ['https://picsum.photos/id/9/300/300'],
        category: 'سيارات',
        subCategory: 'سيارات للبيع',
        sellerId: 'seller3',
        sellerName: 'معرض السيارات',
        sellerRating: 4.6,
        inStock: true,
        rating: 4.6,
        reviewCount: 34,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '5',
        title: 'شقة في حدة - صنعاء',
        description: 'شقة 3 غرف نوم، 2 حمام، صالة كبيرة، موقع مميز',
        price: 35000000,
        currency: 'YER',
        images: ['https://picsum.photos/id/12/300/300'],
        category: 'عقارات',
        subCategory: 'شقق للبيع',
        sellerId: 'seller4',
        sellerName: 'العقارات الذهبية',
        sellerRating: 4.5,
        inStock: true,
        rating: 4.5,
        reviewCount: 12,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '6',
        title: 'غرفة نوم كاملة',
        description: 'غرفة نوم خشب زان - سرير 160 سم، دولاب، تسريحة',
        price: 650000,
        currency: 'YER',
        images: ['https://picsum.photos/id/15/300/300'],
        category: 'أثاث',
        subCategory: 'غرف نوم',
        sellerId: 'seller5',
        sellerName: 'متجر الأثاث',
        sellerRating: 4.3,
        inStock: true,
        rating: 4.3,
        reviewCount: 45,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '7',
        title: 'ثوب رجالي يمني',
        description: 'ثوب يمني تقليدي - قطن 100%، مقاسات مختلفة',
        price: 15000,
        currency: 'YER',
        images: ['https://picsum.photos/id/17/300/300'],
        category: 'ملابس',
        subCategory: 'رجالي',
        sellerId: 'seller6',
        sellerName: 'متجر الملابس',
        sellerRating: 4.6,
        inStock: true,
        rating: 4.6,
        reviewCount: 78,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '8',
        title: 'وجبة مندي دجاج',
        description: 'مندي دجاج مع أرز بسمتي، صلصة، سلطة (تكفي 4 أشخاص)',
        price: 8000,
        currency: 'YER',
        images: ['https://picsum.photos/id/19/300/300'],
        category: 'مطاعم',
        subCategory: 'وجبات رئيسية',
        sellerId: 'seller7',
        sellerName: 'مطعم الأصيل',
        sellerRating: 4.9,
        inStock: true,
        rating: 4.9,
        reviewCount: 234,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '9',
        title: 'صيانة مكيفات',
        description: 'خدمة صيانة وتبريد مكيفات - فحص وتعبئة غاز وتنظيف',
        price: 5000,
        currency: 'YER',
        images: ['https://picsum.photos/id/21/300/300'],
        category: 'خدمات',
        subCategory: 'صيانة',
        sellerId: 'seller8',
        sellerName: 'خدمات الصيانة',
        sellerRating: 4.5,
        inStock: true,
        rating: 4.5,
        reviewCount: 45,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '10',
        title: 'بلاي ستيشن 5',
        description: 'جهاز بلاي ستيشن 5 - نسخة ديجيتال + يد تحكم DualSense',
        price: 250000,
        currency: 'YER',
        images: ['https://picsum.photos/id/23/300/300'],
        category: 'ألعاب',
        subCategory: 'أجهزة ألعاب',
        sellerId: 'seller9',
        sellerName: 'متجر الألعاب',
        sellerRating: 4.9,
        inStock: true,
        rating: 4.9,
        reviewCount: 156,
        createdAt: DateTime.now(),
      ),
    ];
  }
}
