import 'product_model.dart';

class DummyData {
  static List<ProductModel> getProducts() {
    return [
      ProductModel(
        id: '1',
        title: 'آيفون 15 برو ماكس',
        description: 'هاتف أيفون جديد بالكامل مع ضمان سنة',
        price: 450000,
        oldPrice: 500000,
        currency: 'YER',
        images: ['https://picsum.photos/id/1/300/300'],
        category: 'إلكترونيات',
        subCategory: 'هواتف',
        sellerId: 'seller1',
        sellerName: 'متجر التقنية',
        sellerRating: 4.8,
        inStock: true,
        rating: 4.8,
        reviewCount: 120,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '2',
        title: 'سامسونج S24 الترا',
        description: 'هاتف سامسونج جالاكسي S24 الترا',
        price: 380000,
        oldPrice: 420000,
        currency: 'YER',
        images: ['https://picsum.photos/id/3/300/300'],
        category: 'إلكترونيات',
        subCategory: 'هواتف',
        sellerId: 'seller1',
        sellerName: 'متجر التقنية',
        sellerRating: 4.7,
        inStock: true,
        rating: 4.7,
        reviewCount: 95,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '3',
        title: 'ماك بوك برو M3',
        description: 'لابتوب احترافي بشريحة M3',
        price: 1800000,
        currency: 'YER',
        images: ['https://picsum.photos/id/5/300/300'],
        category: 'إلكترونيات',
        subCategory: 'لابتوب',
        sellerId: 'seller2',
        sellerName: 'الحاسوب المتقدم',
        sellerRating: 4.9,
        inStock: true,
        rating: 4.9,
        reviewCount: 45,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '4',
        title: 'تويوتا كامري 2024',
        description: 'سيارة تويوتا كامري 2024',
        price: 8500000,
        currency: 'YER',
        images: ['https://picsum.photos/id/9/300/300'],
        category: 'سيارات',
        subCategory: 'سيارات للبيع',
        sellerId: 'seller3',
        sellerName: 'معرض السيارات',
        sellerRating: 4.6,
        inStock: true,
        rating: 4.6,
        reviewCount: 34,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '5',
        title: 'شقة في حدة',
        description: 'شقة 3 غرف نوم، 2 حمام',
        price: 35000000,
        currency: 'YER',
        images: ['https://picsum.photos/id/12/300/300'],
        category: 'عقارات',
        subCategory: 'شقق للبيع',
        sellerId: 'seller4',
        sellerName: 'العقارات الذهبية',
        sellerRating: 4.5,
        inStock: true,
        rating: 4.5,
        reviewCount: 12,
        createdAt: DateTime.now(),
      ),
    ];
  }
}
